<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Inmate;
use Carbon\Carbon;

class InmateSeeder extends Seeder
{
    public function run()
    {
        $inmates = [
            [
                'inmate_number' => 'INM001',
                'first_name' => 'John',
                'last_name' => 'Smith',
                'date_of_birth' => '1985-03-15',
                'gender' => 'male',
                'admission_date' => '2023-01-15',
                'release_date' => '2028-01-15',
                'sentence_length' => '5 years',
                'crime_category' => 'Drug trafficking',
                'security_level' => 'medium',
                'cell_number' => 'A-101',
                'block' => 'A',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '123 Main St, New York, NY 10001',
                'emergency_contact' => 'Mary Smith (Wife) - 555-0101',
                'next_of_kin' => 'Mary Smith (Wife)',
            ],
            [
                'inmate_number' => 'INM002',
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'date_of_birth' => '1990-07-22',
                'gender' => 'female',
                'admission_date' => '2022-11-08',
                'release_date' => '2027-11-08',
                'sentence_length' => '5 years',
                'crime_category' => 'Fraud',
                'security_level' => 'minimum',
                'cell_number' => 'B-205',
                'block' => 'B',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '456 Oak Ave, Los Angeles, CA 90210',
                'emergency_contact' => 'Robert Johnson (Father) - 555-0202',
                'next_of_kin' => 'Robert Johnson (Father)',
            ],
            [
                'inmate_number' => 'INM003',
                'first_name' => 'Michael',
                'last_name' => 'Davis',
                'date_of_birth' => '1978-12-03',
                'gender' => 'male',
                'admission_date' => '2021-06-20',
                'release_date' => '2031-06-20',
                'sentence_length' => '10 years',
                'crime_category' => 'Armed robbery',
                'security_level' => 'maximum',
                'cell_number' => 'C-301',
                'block' => 'C',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '789 Pine Rd, Chicago, IL 60601',
                'emergency_contact' => 'Lisa Davis (Sister) - 555-0303',
                'next_of_kin' => 'Lisa Davis (Sister)',
            ],
            [
                'inmate_number' => 'INM004',
                'first_name' => 'Emily',
                'last_name' => 'Wilson',
                'date_of_birth' => '1992-04-18',
                'gender' => 'female',
                'admission_date' => '2023-03-10',
                'release_date' => '2026-03-10',
                'sentence_length' => '3 years',
                'crime_category' => 'Theft',
                'security_level' => 'minimum',
                'cell_number' => 'B-210',
                'block' => 'B',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '321 Elm St, Miami, FL 33101',
                'emergency_contact' => 'David Wilson (Brother) - 555-0404',
                'next_of_kin' => 'David Wilson (Brother)',
            ],
            [
                'inmate_number' => 'INM005',
                'first_name' => 'James',
                'last_name' => 'Brown',
                'date_of_birth' => '1982-09-25',
                'gender' => 'male',
                'admission_date' => '2020-12-01',
                'release_date' => '2040-12-01',
                'sentence_length' => 'Life sentence',
                'crime_category' => 'Murder',
                'security_level' => 'supermax',
                'cell_number' => 'D-401',
                'block' => 'D',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '654 Maple Dr, Houston, TX 77001',
                'emergency_contact' => 'Patricia Brown (Mother) - 555-0505',
                'next_of_kin' => 'Patricia Brown (Mother)',
            ],
            [
                'inmate_number' => 'INM006',
                'first_name' => 'Jessica',
                'last_name' => 'Taylor',
                'date_of_birth' => '1988-11-12',
                'gender' => 'female',
                'admission_date' => '2022-08-15',
                'release_date' => '2025-08-15',
                'sentence_length' => '3 years',
                'crime_category' => 'Assault',
                'security_level' => 'medium',
                'cell_number' => 'A-115',
                'block' => 'A',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '987 Cedar Ln, Phoenix, AZ 85001',
                'emergency_contact' => 'Mark Taylor (Husband) - 555-0606',
                'next_of_kin' => 'Mark Taylor (Husband)',
            ],
            [
                'inmate_number' => 'INM007',
                'first_name' => 'David',
                'last_name' => 'Miller',
                'date_of_birth' => '1975-05-30',
                'gender' => 'male',
                'admission_date' => '2021-09-22',
                'release_date' => '2029-09-22',
                'sentence_length' => '8 years',
                'crime_category' => 'Burglary',
                'security_level' => 'medium',
                'cell_number' => 'C-308',
                'block' => 'C',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '147 Birch Way, Denver, CO 80201',
                'emergency_contact' => 'Jennifer Miller (Daughter) - 555-0707',
                'next_of_kin' => 'Jennifer Miller (Daughter)',
            ],
            [
                'inmate_number' => 'INM008',
                'first_name' => 'Amanda',
                'last_name' => 'Anderson',
                'date_of_birth' => '1995-01-08',
                'gender' => 'female',
                'admission_date' => '2023-05-12',
                'release_date' => '2026-05-12',
                'sentence_length' => '3 years',
                'crime_category' => 'Identity theft',
                'security_level' => 'minimum',
                'cell_number' => 'B-220',
                'block' => 'B',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '258 Spruce St, Seattle, WA 98101',
                'emergency_contact' => 'Thomas Anderson (Father) - 555-0808',
                'next_of_kin' => 'Thomas Anderson (Father)',
            ],
            [
                'inmate_number' => 'INM009',
                'first_name' => 'Robert',
                'last_name' => 'Garcia',
                'date_of_birth' => '1980-06-14',
                'gender' => 'male',
                'admission_date' => '2022-02-28',
                'release_date' => '2032-02-28',
                'sentence_length' => '10 years',
                'crime_category' => 'Drug manufacturing',
                'security_level' => 'maximum',
                'cell_number' => 'C-315',
                'block' => 'C',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '369 Willow Ave, San Diego, CA 92101',
                'emergency_contact' => 'Maria Garcia (Wife) - 555-0909',
                'next_of_kin' => 'Maria Garcia (Wife)',
            ],
            [
                'inmate_number' => 'INM010',
                'first_name' => 'Nicole',
                'last_name' => 'Martinez',
                'date_of_birth' => '1993-08-05',
                'gender' => 'female',
                'admission_date' => '2023-07-01',
                'release_date' => '2025-07-01',
                'sentence_length' => '2 years',
                'crime_category' => 'DUI manslaughter',
                'security_level' => 'medium',
                'cell_number' => 'A-125',
                'block' => 'A',
                'status' => 'active',
                'nationality' => 'American',
                'address_before_incarceration' => '741 Poplar Blvd, Portland, OR 97201',
                'emergency_contact' => 'Carlos Martinez (Brother) - 555-1010',
                'next_of_kin' => 'Carlos Martinez (Brother)',
            ],
        ];

        foreach ($inmates as $inmateData) {
            Inmate::create($inmateData);
        }
    }
}
